name: "Hello .NET"

on:
  workflow_dispatch:
  push:

env:
  PROJECT_PATH: Notes.Api.Test/Notes.Api.Test.csproj

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Setup .NET Core SDK"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: "Print .NET CLI version"
        run: dotnet --version
      - name: "Restore packages"
        run: "dotnet restore $PROJECT_PATH"
      - name: "Build project"
        run: "dotnet build $PROJECT_PATH --no-restore --configuration Release"
      - name: "Run tests"
        run: "dotnet test $PROJECT_PATH --no-build --configuration Release --logger trx"
      - name: "Test report"
        uses: "dorny/test-reporter@v1"
        if: success() || failure()
        with:
          name: test-report
          path: Notes.Api.Test/TestResults/*.trx
          reporter: dotnet-trx